spring:
  profiles:
    active: local # 기본적으로 local이 선택된다는 뜻
  mvc:
    view:
      prefix: /WEB-INF/jsp/ 
      suffix: .jsp
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/a7?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC # DB명 치환
    username: root # DB아이디 치환
    password:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB      
  mail:
    host: smtp.gmail.com
    port: 587
    username: GMAIL아이디 # GMAIL아이디 치환
    password: GMAIL비번 # GMAIL비번 치환
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
mybatis:
  type-aliases-package: com.example.sbs.demo.dto # dto의 풀 패키지 명 입력
custom:
  logoText: CUNI # 사이트 명 치환
  uploadDir: C:/work/abc/uploads # 파일업로드 되는 곳 치환
  emailSender: no-reply@noreply.com # 사이트 메일 발신자 이름으로 치환
  emailSenderName: CUNI Master # 사이트 운영자 명으로 치환

---

spring:
  profiles: local
server:
  port: 8085 # 포트번호 치환

---

# 운영환경만의 설정
spring:
  profiles: production
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/DB명?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC # DB명 치환(서비스 용)
    username: DB아이디 # DB아이디 치환(서비스 용)
    password: DB비번 # DB비번 치환(서비스 용)
logging:
  level:
    root: info
server:
  port: 8086 # 포트번호 치환(서비스 용)
custom:
  uploadDir: C:/work/abc/uploads # 파일업로드 되는 곳 치환(서비스용)
